### ISSUE TITLE
RuntimeError: ffi_prep_cif_var failed

### ISSUE THREAD

**Issue by wutong4012** [Danial-Alh/fast-bleu#16]
When I run the test_case.py on Linux, I got this error.

tokenized!
Traceback (most recent call last):
  File "test_cases.py", line 96, in <module>
    compare(nltk_org_bleu, cpp_bleu)
  File "test_cases.py", line 65, in compare
    cpp_result, cpp_time = get_execution_time(cpp_func)
  File "test_cases.py", line 59, in get_execution_time
    result = np.array(func(ref_tokens, test_tokens))
  File "test_cases.py", line 31, in cpp_bleu
    bleu = BLEU(refs, w, verbose=True)
  File "/wutong/fast-bleu/fast_bleu/__python_wrapper__.py", line 85, in __init__
    self.__instance = self.__get_instance(
RuntimeError: ffi_prep_cif_var failed

Could you tell me how to solve it? Thanks!

**Comment by wutong4012** [comment]
OK. I solve it by "conda install -c conda-forge libffi=3.3.*".
